'use client';
/* oxlint-disable typescript/no-explicit-any, jsx-a11y/prefer-tag-over-role -- Dynamic aggregate metrics and an accessible chart summary require runtime records. */

import {useId,useMemo,useState} from 'react';
import {BarChart2,Shield,Target,Users} from 'lucide-react';
import {aggregate,type Match,result} from '@/lib/domain';
interface AnalyticsCenterProps{matches:Match[];players:any[];teamName:string}
type View='summary'|'attack'|'defence'|'players'|'rivals';
type AggregatePlayer=ReturnType<typeof aggregate>[number];
const fmt=(n:number|null|undefined,d=0)=>n==null?'—':n.toLocaleString('pt-BR',{maximumFractionDigits:d});
const date=(s:string)=>new Date(s).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'});

export function AnalyticsCenter({matches,teamName}:AnalyticsCenterProps){
 const [view,setView]=useState<View>('summary');const [query,setQuery]=useState('');const tabsId=useId();
 const valid=useMemo(()=>matches.filter(m=>!m.excluded&&m.type==='friendlyMatch'),[matches]);
 const players=useMemo(()=>aggregate(valid),[valid]);
 const stats=useMemo(()=>{const ownLines=valid.flatMap(m=>m.players.filter(p=>p.own));const sum=(key:'shots'|'passes'|'passAttempts'|'tackles'|'tackleAttempts'|'saves'|'redCards'|'motm'|'assists'|'goals'|'seconds')=>{const rows=ownLines.map(p=>p[key]).filter((v):v is number=>v!==null);return rows.length?rows.reduce((n,v)=>n+v,0):null};const total=valid.length,wins=valid.filter(m=>result(m)==='V').length,draws=valid.filter(m=>result(m)==='E').length,gf=valid.reduce((n,m)=>n+m.goalsFor,0),ga=valid.reduce((n,m)=>n+m.goalsAgainst,0),shots=sum('shots'),passes=sum('passes'),passAttempts=sum('passAttempts'),tackles=sum('tackles'),tackleAttempts=sum('tackleAttempts'),ratings=ownLines.map(p=>p.rating).filter((v):v is number=>v!==null);return{total,wins,draws,losses:total-wins-draws,gf,ga,points:total?(wins*3+draws)/(total*3)*100:0,clean:valid.filter(m=>m.goalsAgainst===0).length,shots,conversion:shots?gf/shots*100:null,passes,passAttempts,passAccuracy:passAttempts?Number(passes??0)/passAttempts*100:null,tackles,tackleRate:tackleAttempts?Number(tackles??0)/tackleAttempts*100:null,saves:sum('saves'),redCards:sum('redCards'),motm:sum('motm'),assists:sum('assists'),playerGoals:sum('goals'),minutes:(sum('seconds')??0)/60,averageRating:ratings.length?ratings.reduce((n,v)=>n+v,0)/ratings.length:null,playerGames:players.filter(p=>Number(p.games)>0).length}},[valid,players]);
 const rivals=useMemo(()=>{const map=new Map<string,any>();for(const m of valid){const k=m.opponent||'Desconhecido',v=map.get(k)??{name:k,games:0,wins:0,draws:0,losses:0,gf:0,ga:0,last:m.playedAt};v.games++;v.gf+=m.goalsFor;v.ga+=m.goalsAgainst;const r=result(m);if(r==='V')v.wins++;else if(r==='E')v.draws++;else v.losses++;if(Date.parse(m.playedAt)>Date.parse(v.last))v.last=m.playedAt;map.set(k,v)}return[...map.values()].filter(v=>v.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.games-a.games)},[valid,query]);
 const leaders=(key:keyof AggregatePlayer)=>[...players].filter(p=>Number(p[key])>0).sort((a,b)=>Number(b[key])-Number(a[key])).slice(0,5);
 const coverage=[{label:'Amistosos válidos',value:stats.total,ok:stats.total>=5},{label:'Jogadores com amostra',value:stats.playerGames,ok:stats.playerGames>=5},{label:'Finalizações registradas',value:stats.shots,ok:stats.shots!==null},{label:'Tentativas de passe',value:stats.passAttempts,ok:stats.passAttempts!==null}];
 const insights=[stats.points>=60?`Aproveitamento forte: ${fmt(stats.points,1)}% na amostra.`:stats.points>=40?`Aproveitamento estável: ${fmt(stats.points,1)}%; há margem para evolução.`:`Aproveitamento de ${fmt(stats.points,1)}% pede revisão do plano.`,stats.gf>stats.ga?`Saldo positivo de ${stats.gf-stats.ga} gols.`:stats.gf===stats.ga?'Ataque e defesa estão equilibrados no saldo.':`Saldo negativo de ${stats.ga-stats.gf} gols; proteção da área é prioridade.`,stats.total<5?'Amostra curta: trate tendências como sinais, não conclusões.':stats.total<10?'Amostra moderada: confirme padrões com vídeo.':'Amostra consistente para leitura de tendências.'];
 const tabs:[View,string][]=[['summary','Visão executiva'],['attack','Ataque'],['defence','Defesa'],['players','Jogadores'],['rivals','Rivais']];
 if(!stats.total)return <div className="analytics-empty"><BarChart2 size={36}/><h3>Análises ainda sem amistosos</h3><p>Somente amistosos válidos da EA entram nesta central. Liga, playoffs, partidas manuais e GlobalPro não são misturados.</p></div>;
 return <section className="analytics-center-container analytics-workroom" aria-label={`Análises de ${teamName}`}>
  <header className="analytics-command-bar"><div><h2>Leitura de amistosos</h2><p>Somente dados reais retornados pela EA; campos ausentes não são estimados.</p></div><div className="analytics-sample"><strong>{stats.total}</strong><span>amistosos válidos</span></div></header>
  <div className="analytics-tabs" role="tablist" aria-label="Áreas da análise">{tabs.map(([id,label])=><button key={id} id={`${tabsId}-${id}`} role="tab" aria-selected={view===id} aria-controls={`${tabsId}-panel`} tabIndex={view===id?0:-1} className={`analytics-tab ${view===id?'active':''}`} onClick={()=>setView(id)}>{label}</button>)}</div>
  <div id={`${tabsId}-panel`} role="tabpanel" aria-labelledby={`${tabsId}-${view}`} className="analytics-view">
   {view==='summary'&&<><div className="analytics-kpi-grid"><Kpi label="Aproveitamento" value={`${fmt(stats.points,1)}%`} detail={`${stats.wins}V · ${stats.draws}E · ${stats.losses}D`}/><Kpi label="Gols por jogo" value={fmt(stats.gf/stats.total,2)} detail={`${stats.gf} marcados`}/><Kpi label="Gols sofridos/jogo" value={fmt(stats.ga/stats.total,2)} detail={`${stats.ga} sofridos`}/><Kpi label="Jogos sem sofrer" value={stats.clean} detail={`${fmt(stats.clean/stats.total*100,1)}% da amostra`}/></div><div className="analytics-two-columns"><article className="analytics-panel insight-panel"><h3>Briefing executivo</h3><ol className="insight-list">{insights.map((text,n)=><li key={text}><span>{String(n+1).padStart(2,'0')}</span><p>{text}</p></li>)}</ol></article><Coverage rows={coverage}/></div><Trend matches={valid.slice(0,10).reverse()}/></>}
   {view==='attack'&&<><MetricPanel icon={<Target/>} title="Produção ofensiva" items={[['Gols do placar',stats.gf],['Gols individuais',stats.playerGoals],['Assistências',stats.assists],['Finalizações',stats.shots],['Conversão',stats.conversion==null?'Sem cobertura':`${fmt(stats.conversion,1)}%`]]}/><Ranking title="Artilharia" rows={leaders('goals')} metric="goals" suffix="gols"/><Ranking title="Criação" rows={leaders('assists')} metric="assists" suffix="assistências"/></>}
   {view==='defence'&&<><MetricPanel icon={<Shield/>} title="Proteção e recuperação" items={[['Gols sofridos',stats.ga],['Jogos sem sofrer',stats.clean],['Desarmes',stats.tackles],['Eficiência de desarme',stats.tackleRate==null?'Sem cobertura':`${fmt(stats.tackleRate,1)}%`],['Defesas',stats.saves],['Cartões vermelhos',stats.redCards]]}/><Ranking title="Recuperadores" rows={leaders('tackles')} metric="tackles" suffix="desarmes"/><Ranking title="Defesas registradas" rows={leaders('saves')} metric="saves" suffix="defesas"/></>}
   {view==='players'&&<><MetricPanel icon={<Users/>} title="Cobertura individual" items={[['Jogadores na amostra',stats.playerGames],['Atuações com nota',players.reduce((n,p)=>n+(p.ratings??0),0)],['Nota média',stats.averageRating==null?'Sem cobertura':fmt(stats.averageRating,2)],['Minutos registrados',stats.minutes?fmt(stats.minutes,0):'Sem cobertura'],['Passes certos',stats.passes],['Tentativas de passe',stats.passAttempts],['Precisão de passe',stats.passAccuracy==null?'Sem cobertura':`${fmt(stats.passAccuracy,1)}%`],['MVPs',stats.motm]]}/><Ranking title="Participação" rows={[...players].sort((a,b)=>Number(b.goals??0)+Number(b.assists??0)-Number(a.goals??0)-Number(a.assists??0)).slice(0,8)} metric="games" suffix="jogos"/><Ranking title="Melhores notas" rows={[...players].filter(p=>p.rating!==null).sort((a,b)=>Number(b.rating)-Number(a.rating)).slice(0,5)} metric="rating" suffix="de nota"/></>}
   {view==='rivals'&&<article className="analytics-panel"><header className="panel-header-custom"><div><h3>Retrospecto por rival</h3><p>Resultados observados no histórico selecionado.</p></div><label className="analytics-search"><span>Buscar rival</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome do adversário"/></label></header><div className="table-wrap"><table className="h2h-table"><caption className="sr-only">Retrospecto de {teamName} por adversário</caption><thead><tr><th scope="col">Adversário</th><th scope="col">J</th><th scope="col">V-E-D</th><th scope="col">Aproveitamento</th><th scope="col">Gols</th><th scope="col">Último jogo</th></tr></thead><tbody>{rivals.map(r=><tr key={r.name}><th scope="row">{r.name}</th><td>{r.games}</td><td>{r.wins}-{r.draws}-{r.losses}</td><td>{fmt((r.wins*3+r.draws)/(r.games*3)*100,1)}%</td><td>{r.gf}–{r.ga}</td><td>{date(r.last)}</td></tr>)}</tbody></table></div>{!rivals.length&&<p className="analytics-no-results">Nenhum rival encontrado.</p>}</article>}
  </div>
 </section>;
}
function Kpi({label,value,detail}:{label:string;value:any;detail:string}){return <article className="kpi-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Coverage({rows}:{rows:{label:string;value:number|null;ok:boolean}[]}){return <article className="analytics-panel coverage-panel"><h3>Cobertura dos dados</h3><p>Ausência de dados não é estimada.</p><ul>{rows.map(r=><li key={r.label}><span>{r.label}</span><b>{r.value??'—'}</b><small className={r.ok?'coverage-ok':'coverage-limited'}>{r.ok?'Disponível':'Limitada'}</small></li>)}</ul></article>}
function Trend({matches}:{matches:Match[]}){const max=Math.max(1,...matches.flatMap(m=>[m.goalsFor,m.goalsAgainst]));return <article className="analytics-panel trend-panel"><header><h3>Últimos resultados</h3><p>Valores visíveis além da cor.</p></header><div className="trend-chart" role="img" aria-label={matches.map(m=>`${m.opponent}: ${m.goalsFor} a ${m.goalsAgainst}`).join('; ')}>{matches.map(m=><div className="trend-match" key={m.id}><div className="trend-bars" aria-hidden="true"><span className="trend-for" style={{height:`${Math.max(8,m.goalsFor/max*100)}%`}}/><span className="trend-against" style={{height:`${Math.max(8,m.goalsAgainst/max*100)}%`}}/></div><b>{m.goalsFor}–{m.goalsAgainst}</b><small>{m.opponent}</small></div>)}</div><details className="trend-data"><summary>Ver dados do gráfico</summary><div className="table-wrap"><table><thead><tr><th scope="col">Adversário</th><th scope="col">Pró</th><th scope="col">Contra</th><th scope="col">Resultado</th></tr></thead><tbody>{matches.map(m=><tr key={m.id}><th scope="row">{m.opponent}</th><td>{m.goalsFor}</td><td>{m.goalsAgainst}</td><td>{result(m)}</td></tr>)}</tbody></table></div></details></article>}
function MetricPanel({icon,title,items}:{icon:any;title:string;items:[string,any][]}){return <article className="analytics-panel metric-panel"><header><div>{icon}<h3>{title}</h3></div><p>Valores disponíveis na amostra atual.</p></header><dl>{items.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v==null?'Sem cobertura':v}</dd></div>)}</dl></article>}
function Ranking({title,rows,metric,suffix}:{title:string;rows:any[];metric:string;suffix:string}){return <article className="analytics-panel ranking-panel"><h3>{title}</h3>{rows.length?<ol>{rows.map((p,i)=><li key={p.id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{p.name}</b><small>{p.position||'Posição não informada'}</small></div><strong>{fmt(p[metric])} {suffix}</strong></li>)}</ol>:<p className="muted-empty">Sem dados suficientes para este ranking.</p>}</article>}
