'use client';
/* oxlint-disable typescript/no-explicit-any, jsx-a11y/control-has-associated-label, jsx-a11y/prefer-tag-over-role -- Dynamic historical rows use visually hidden/context labels and modal semantics. */
import {useMemo,useState} from 'react';
import {ArrowLeft,ChevronRight,ClipboardCheck,Search,Star,Trash2} from 'lucide-react';
import type {Match,RecordItem} from '@/lib/domain';
type AppRecord=RecordItem<Record<string,any>>;
type Props={matches:Match[];records:AppRecord[];admin:boolean;saveRecord:(kind:string,data:any,id?:string)=>Promise<void>;removeRecord:(r:AppRecord)=>Promise<void>};
const date=(s:string)=>new Date(s).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
const pos=(raw:string)=>{const p=String(raw||'').toUpperCase();if(/GK|GOL/.test(p))return'GOL';if(/CB|LB|RB|DEF|ZAG|LAT/.test(p))return'DEF';if(/CM|CAM|CDM|LM|RM|MEI|VOL/.test(p))return'MEI';if(/ST|LW|RW|ATA|PE|PD/.test(p))return'ATA';return'OUT'};
export function MarketWatchlist({matches,records,admin,saveRecord,removeRecord}:Props){
 const [query,setQuery]=useState('');const [position,setPosition]=useState('all');const [pipeline,setPipeline]=useState('all');const [selectedId,setSelectedId]=useState('');const [editing,setEditing]=useState<any>(null);const [status,setStatus]=useState('Em observação');const [priority,setPriority]=useState('Média');const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const targets=useMemo(()=>records.filter(r=>r.kind==='scout_target'),[records]);
 const players=useMemo(()=>{const map=new Map<string,any>();for(const m of matches){if(m.excluded)continue;for(const p of m.players||[]){if(p.own)continue;const x=map.get(p.id)??{id:p.id,name:p.name,position:p.position,clubs:new Set<string>(),games:0,goals:0,assists:0,shots:0,tackles:0,seconds:0,sum:0,ratings:0,lastSeen:m.playedAt,appearances:[]};x.games++;x.clubs.add(m.opponent);x.goals+=p.goals??0;x.assists+=p.assists??0;x.shots+=p.shots??0;x.tackles+=p.tackles??0;x.seconds+=p.seconds??0;if(p.rating!=null){x.sum+=p.rating;x.ratings++}if(m.playedAt>x.lastSeen)x.lastSeen=m.playedAt;x.appearances.push({match:m,line:p});map.set(p.id,x)}}return [...map.values()].map(p=>{const target=targets.find(r=>r.data.playerId===p.id);const mean=p.ratings?p.sum/p.ratings:null;return {...p,clubs:[...p.clubs],mean,target,confidence:p.ratings>=5?'Alta':p.ratings>=2?'Média':'Baixa'}}).sort((a,b)=>(b.mean??-1)-(a.mean??-1)||b.games-a.games)},[matches,targets]);
 const filtered=players.filter(p=>(!query||`${p.name} ${p.clubs.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(position==='all'||pos(p.position)===position)&&(pipeline==='all'||(pipeline==='shortlist'?!!p.target:p.target?.data.status===pipeline)));const selected=players.find(p=>p.id===selectedId)??filtered[0];
 async function save(){if(!editing)return;setBusy(true);setError('');try{await saveRecord('scout_target',{playerId:editing.id,playerName:editing.name,position:editing.position,status,priority,notes,updatedAt:new Date().toISOString()},editing.target?.id);setEditing(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function edit(p:any){setEditing(p);setStatus(p.target?.data.status||'Em observação');setPriority(p.target?.data.priority||'Média');setNotes(p.target?.data.notes||'');setError('')}
 return <div className="market-container"><div className="scouting-header-box"><div className="scouting-title-wrap"><h2>Pipeline de jogadores observados</h2><p>Compare somente atletas enfrentados. A confiança reflete quantas atuações possuem nota, não uma projeção de potencial.</p></div></div>
 <div className="toolbar"><label className="search"><Search size={17} aria-hidden="true"/><input aria-label="Buscar jogador ou clube" placeholder="Jogador ou clube" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar posição" value={position} onChange={e=>setPosition(e.target.value)}><option value="all">Todas as posições</option><option>GOL</option><option>DEF</option><option>MEI</option><option>ATA</option></select><select aria-label="Filtrar pipeline" value={pipeline} onChange={e=>setPipeline(e.target.value)}><option value="all">Todo o radar</option><option value="shortlist">Na shortlist</option><option>Em observação</option><option>Contato sugerido</option><option>Descartado</option></select></div>
 <div className="overview-grid"><section className="panel"><header><h2>Radar comparável</h2><span className="muted">{filtered.length} atletas</span></header>{filtered.length?<div className="table-wrap"><table><thead><tr><th>Jogador</th><th>Clube(s)</th><th>Pos.</th><th>Amostra</th><th>Nota</th><th>Confiança</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className={selected?.id===p.id?'active':''}><td><button className="text-button" onClick={()=>setSelectedId(p.id)}><b>{p.name}</b></button></td><td>{p.clubs.slice(0,2).join(', ')}</td><td>{pos(p.position)}</td><td>{p.games} jogos · {p.ratings} notas</td><td>{p.mean?p.mean.toLocaleString('pt-BR',{maximumFractionDigits:1}):'Sem dado'}</td><td><span className="tag">{p.confidence}</span></td><td>{p.target?.data.status||'Radar'}</td><td><button className="icon-button" aria-label={`Abrir detalhes de ${p.name}`} onClick={()=>setSelectedId(p.id)}><ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>:<div className="empty"><Search size={24}/><h3>Nenhum atleta encontrado</h3><p>Refine os filtros ou aguarde partidas com estatísticas adversárias.</p></div>}</section>
 <aside className="panel">{selected?<><header><div><button className="text-button" onClick={()=>setSelectedId('')}><ArrowLeft size={14}/> Voltar</button><h2>{selected.name}</h2><small>{selected.clubs.join(', ')}</small></div>{selected.target&&admin&&<button className="icon-button" aria-label={`Remover ${selected.name} da shortlist`} onClick={()=>void removeRecord(selected.target)}><Trash2 size={16}/></button>}</header><div className="metrics"><div className="metric"><span>Jogos</span><strong>{selected.games}</strong><small>{selected.ratings} com nota</small></div><div className="metric"><span>Nota média</span><strong>{selected.mean?selected.mean.toLocaleString('pt-BR',{maximumFractionDigits:1}):'—'}</strong><small>confiança {selected.confidence.toLowerCase()}</small></div><div className="metric"><span>Participações</span><strong>{selected.goals+selected.assists}</strong><small>{selected.goals} gols · {selected.assists} assist.</small></div></div>
 {selected.seconds>0&&<div className="form-strip"><span>POR 90 MIN</span><b>{(selected.goals/(selected.seconds/5400)).toLocaleString('pt-BR',{maximumFractionDigits:2})} gols</b><b>{(selected.assists/(selected.seconds/5400)).toLocaleString('pt-BR',{maximumFractionDigits:2})} assist.</b><small>{Math.round(selected.seconds/60)} minutos registrados</small></div>}
 {selected.target&&<div className="ai-analysis-pro"><div className="ai-header"><ClipboardCheck size={16}/><b>{selected.target.data.status} · prioridade {selected.target.data.priority||'não definida'}</b></div><p>{selected.target.data.notes||'Sem notas da diretoria.'}</p></div>}{admin&&<button className="button primary" onClick={()=>edit(selected)}><Star size={15}/>{selected.target?'Atualizar avaliação':'Adicionar à shortlist'}</button>}
 <div className="section-title-bar"><div><h3>Atuações que sustentam a leitura</h3><p>Abra Partidas para consultar a ficha completa.</p></div></div>{selected.appearances.sort((a:any,b:any)=>b.match.playedAt.localeCompare(a.match.playedAt)).slice(0,8).map((a:any)=><div className="list-row" key={a.match.id}><span>{date(a.match.playedAt)}</span><b>por {a.match.opponent}</b><strong>{a.line.rating!=null?`Nota ${a.line.rating}`:'Sem nota'}</strong></div>)}</>:<div className="empty"><Search size={24}/><h3>Selecione um atleta</h3><p>O detalhe da amostra aparecerá aqui.</p></div>}</aside></div>
 {editing&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="watch-title"><header><h2 id="watch-title">Avaliar {editing.name}</h2><button className="icon-button" aria-label="Fechar avaliação" onClick={()=>setEditing(null)}>×</button></header><div className="data-form"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>Em observação</option><option>Contato sugerido</option><option>Descartado</option></select></label><label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Alta</option><option>Média</option><option>Baixa</option></select></label><label>Notas da diretoria<textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Contexto, encaixe e pontos a validar"/></label>{error&&<p role="alert" className="error-text">{error}</p>}<button className="button primary" disabled={busy} onClick={()=>void save()}>{busy?'Salvando…':'Salvar avaliação'}</button></div></section></div>}</div>
}
