import { env } from 'cloudflare:workers';
import { cookies } from 'next/headers';
import { isTeam, type TeamId } from './domain';
type RuntimeEnv={DB:D1Database;MEDIA:R2Bucket;[key:string]:unknown};
export type AppConfig={clubId?:string;platform:string;edition:string;formation:string;name:string;logo?:string;discordWebhook?:string;geminiKey?:string;geminiModel?:string;passwordHash?:string;passwordSalt?:string;viewerHash?:string;accessVersion?:number};
type SessionRow={role:string;version:number};
export function db(){return (env as unknown as RuntimeEnv).DB}
export function media(){return (env as unknown as RuntimeEnv).MEDIA}
export function secret(key:string){const value=(env as unknown as RuntimeEnv)[key];return typeof value==='string'?value:''}
export class AppError extends Error{constructor(message:string,public status=400){super(message)}}
export const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff'}});
export const fail=(e:unknown)=>json({error:e instanceof AppError?e.message:'Não foi possível concluir. Tente novamente.'},e instanceof AppError?e.status:500);
export async function hash(text:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function equal(a:string,b:string){return await hash(a)===await hash(b)}
export function random(){return crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','')}
export async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function config(team:TeamId):Promise<AppConfig>{const row=await db().prepare('SELECT data FROM settings WHERE team = ?').bind(team).first<{data:string}>();return row?JSON.parse(row.data) as AppConfig:{clubId:'',platform:'common-gen5',edition:'fc',formation:'4-3-3',name:team==='dtr'?'DTR Esports':'Vortex EC'}}
export async function setConfig(team:TeamId,data:AppConfig){await db().prepare('INSERT INTO settings (team, data) VALUES (?, ?) ON CONFLICT(team) DO UPDATE SET data=excluded.data').bind(team,JSON.stringify(data)).run()}
export async function session(team:string,admin=false){if(!isTeam(team))throw new AppError('Equipe não encontrada.',404);const jar=await cookies();const token=jar.get(`tl_${team}`)?.value;if(!token)throw new AppError('Abra o link privado da sua equipe.',401);const s=await db().prepare('SELECT role, version FROM sessions WHERE team = ? AND token = ? AND expires > ?').bind(team,await hash(token),Date.now()).first<SessionRow>();if(!s)throw new AppError('Seu acesso expirou. Abra novamente o link da equipe.',401);const c=await config(team);if(s.version!==(c.accessVersion??0))throw new AppError('Link alterado. Solicite o novo acesso.',401);if(admin&&s.role!=='admin')throw new AppError('Entre com a senha administrativa.',403);return {team,role:s.role,config:c}}
export async function createSession(team:TeamId,role:string){const token=random();const c=await config(team);const maxAge=role==='admin'?28800:604800;await db().prepare('INSERT INTO sessions (token, team, role, version, expires) VALUES (?, ?, ?, ?, ?)').bind(await hash(token),team,role,c.accessVersion??0,Date.now()+maxAge*1000).run();return {token,maxAge}}
export async function revokeCurrent(team:TeamId){const jar=await cookies();const token=jar.get(`tl_${team}`)?.value;if(token)await db().prepare('DELETE FROM sessions WHERE team=? AND token=?').bind(team,await hash(token)).run()}
export function cookie(team:string,token:string,maxAge:number,request:Request){return `tl_${team}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${new URL(request.url).protocol==='https:'?'; Secure':''}`}
export function sameOrigin(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)throw new AppError('Origem da solicitação inválida.',403)}
export async function readLimited(request:Request,limit=2000000){if(Number(request.headers.get('content-length')??0)>limit)throw new AppError('Arquivo muito grande. Limite de 2 MB.',413);const reader=request.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new AppError('Arquivo muito grande. Limite de 2 MB.',413)}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes}
export async function body<T>(request:Request):Promise<T>{const bytes=await readLimited(request);try{return JSON.parse(new TextDecoder().decode(bytes)) as T}catch{throw new AppError('JSON inválido.')}}
export async function audit(team:TeamId,action:string,detail:string){await db().prepare('INSERT INTO audit (id, team, action, detail, at) VALUES (?, ?, ?, ?, ?)').bind(crypto.randomUUID(),team,action,detail,new Date().toISOString()).run()}
export async function rateLimit(team:TeamId,request:Request){const key=await hash(`${team}:${request.headers.get('cf-connecting-ip')??'local'}`);const now=Date.now();await db().prepare('INSERT INTO attempts (id, count, until) VALUES (?, 1, ?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN attempts.until < ? THEN 1 ELSE attempts.count+1 END, until=CASE WHEN attempts.until < ? THEN excluded.until ELSE attempts.until END').bind(key,now+900000,now,now).run();const row=await db().prepare('SELECT count FROM attempts WHERE id=?').bind(key).first<{count:number}>();if(row&&row.count>10)throw new AppError('Muitas tentativas. Aguarde 15 minutos.',429)}
